apiVersion: v2
name: bank
version: 0.1.0
appVersion: "0.1.0"
description: Зонтичный Helm чарт для bank
type: application
dependencies:
  - name: exchange-service
    version: "0.1.0"
    repository: "file://./charts/exchange-service"
  - name: notifications-service
    version: "0.1.0"
    repository: "file://./charts/notifications-service"
  - name: postgresql
    version: "14.2.3"
    repository: "https://charts.bitnami.com/bitnami"
    alias: db
    condition: db.enabled
  - name: keycloak
    version: "24.7.3"
    repository: "https://charts.bitnami.com/bitnami"
    alias: keycloak
    condition: keycloak.enabled
  - name: blocker-service
    version: "0.1.0"
    repository: "file://./charts/blocker-service"
  - name: exchange-service
    version: "0.1.0"
    repository: "file://./charts/exchange-service"
  - name: account-service
    version: "0.1.0"
    repository: "file://./charts/account-service"
  - name: cash-service
    version: "0.1.0"
    repository: "file://./charts/cash-service"
  - name: transfer-service
    version: "0.1.0"
    repository: "file://./charts/transfer-service"
  - name: bank-ui
    version: "0.1.0"
    repository: "file://./charts/bank-ui"
  - name: kafka
    version: "27.1.2"
    repository: "https://charts.bitnami.com/bitnami"
    alias: kafka
    condition: kafka.enabled
  - name: zipkin
    version: "1.3.5"
    repository: "https://charts.bitnami.com/bitnami"
  - name: elasticsearch
    version: "22.0.9"
    repository: "https://charts.bitnami.com/bitnami"
    alias: elasticsearch
  - name: logstash
    version: "7.0.5"
    repository: "https://charts.bitnami.com/bitnami"
    alias: logstash
  - name: kibana
    version: "12.1.4"
    repository: "https://charts.bitnami.com/bitnami"
    alias: kibana
  - name: grafana
    version: "12.0.8"
    repository: "https://charts.bitnami.com/bitnami"
    alias: grafana
  - name: kube-prometheus
    version: "11.2.6"
    repository: "https://charts.bitnami.com/bitnami"
    alias: kube-prometheus
