# Global values (if any)
global:
  domain: bank.local # Example domain for ingress

# Configuration for the customer-service subchart
# NOTE: For local development (Minikube/Kind/Docker Desktop), build the image locally
# (e.g., `docker build -t customer-service:0.0.1-SNAPSHOT .` in customer-service dir)
# and ensure your K8s cluster can access local images (e.g., `minikube docker-env` or `kind load docker-image ...`).
exchange-service:
  replicaCount: 1
  image:
    # --- REVERTED TO LOCAL REPO ---
    repository: exchange-service # Removed registry prefix
    tag: "0.0.1-SNAPSHOT"
    pullPolicy: IfNotPresent # Use IfNotPresent for local images
    # -----------------------------
  service:
    type: ClusterIP
    port: 8091
  keycloak:
    issuer_uri: "http://bank-keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/realms/bank"
    token_uri: "http://bank-keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/realms/bank/protocol/openid-connect/token"
  ingress:
    enabled: true
    className: "nginx"
    annotations: {}
    hosts:
      - host: exchange-service.bank.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: [ ]
  gateway:
    service_url: "http://exchange-service.{{ .Release.Namespace }}.svc.cluster.local:8087"

notifications-service:
  replicaCount: 1
  image:
    repository: notifications-service
    tag: "0.0.1-SNAPSHOT"
    pullPolicy: IfNotPresent
    # -----------------------------
  service:
    type: ClusterIP
    port: 8081
  ingress:
    enabled: true
    className: "nginx"
    annotations: {}
    hosts:
      - host: notifications-service.bank.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: [ ]
  keycloak:
    issuer_uri: "http://bank-keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/realms/bank"
    token_uri: "http://bank-keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/realms/bank/protocol/openid-connect/token"
  config:
    database_url: "jdbc:postgresql://bank-db.{{ .Release.Namespace }}.svc.cluster.local:5432/bank"
    database_username: "bank"


db:
  enabled: true
  auth:
    enablePostgresUser: true
    postgresPassword: "12345" # Можно оставить пустым для генерации
    database: bank
    username: bank
    password: "123456" # Example: Not recommended for production
  primary:
    persistence:
      enabled: true
      size: 1Gi # Small size for example
    pgHbaConfiguration: |
      # Локальные соединения без пароля - для тестирования, не для прода
      local   all             all                                     trust
      host    replication     all                   127.0.0.1/32    md5
      host    replication     all                   ::1/128         md5
      host    all             all                   0.0.0.0/0       md5
      host    all             all                   ::/0            md5

keycloak:
  enabled: true
  auth:
    adminUser: admin
    adminPassword: adminpassword
  httpRelativePath: "/"
  hostname: localhost
  production: false
  tls:
    enabled: false
  service:
    type: ClusterIP
    ports:
      http: 8080
  extraArgs:
    - --import-realm
  extraVolumes:
    - name: realm-config
      configMap:
        name: keycloak-realm-config
  extraVolumeMounts:
    - name: realm-config
      mountPath: /opt/bitnami/keycloak/data/import
  extraEnvVars:
    - name: KEYCLOAK_EXTRA_ARGS
      value: --import-realm