spring:
  application:
    name: blockerService
  cloud:
    config:
      enabled: false
  datasource:
    initialization-mode: never
    enabled: false
  liquibase:
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8282/realms/bank
server:
  port: 8085
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/