spring:
  application:
    name: exchangeService
  datasource:
    url: jdbc:postgresql://localhost:5433/bank
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8282/realms/bank
  kafka:
    bootstrap-servers: bolohonov.kafka.ru:9092
    consumer:
      group-id: currency-rate-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        acks: all
    listener:
      observation-enabled: true
      ack-mode: RECORD
    admin:
      client-id: bank-app
    properties:
      security.protocol: PLAINTEXT
    template:
      observation-enabled: true
server:
  port: 8087
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
bank:
  gateway: http://localhost:8084/
logging:
  level:
    liquibase: DEBUG

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
