apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: exchange-service
  template:
    metadata:
      labels:
        app: exchange-service
    spec:
      containers:
        - name: exchange-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            # Указывает Spring искать конфигурацию в /app/config/
            - name: SPRING_CONFIG_LOCATION
              value: file:///app/config/
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "exchange-service.fullname" . }}
