spring:
  application:
    name: configservice
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/properties/

server:
  port: ${CONFIG_SERVER_PORT:8088}
